---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-builder
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-builder
rules:
  - apiGroups: ["build.openshift.io"]
    resources: ["builds", "buildconfigs", "buildconfigs/instantiate", "buildconfigs/instantiatebinary"]
    verbs: ["get", "list", "create", "update"]
  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreams", "imagestreamtags"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["operator.openshift.io"]
    resources: ["consoles"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-builder
subjects:
  - kind: ServiceAccount
    name: console-builder
    namespace: {{ .Values.namespace }}
