{{- range .Values.servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-mcp
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ .name }}-mcp
  ports:
    - port: 8080
      targetPort: 8000
      protocol: TCP
{{- end }}
