{{- if .Values.bookinfo.enabled }}
{{- $ns := .Values.bookinfo.namespace }}
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: {{ $.Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  hosts:
  - "*"
  gateways:
  - {{ $.Values.istio.namespace }}/bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
{{- end }}
