---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: {{ .Values.istio.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  version: {{ .Values.kiali.version }}
  auth:
    strategy: openshift
  external_services:
    grafana:
      enabled: false
    tracing:
      enabled: true
      provider: tempo
      internal_url: http://tempo-tempo-query-frontend.{{ .Values.tempo.namespace }}:3200
      in_cluster_url: http://tempo-tempo-query-frontend.{{ .Values.tempo.namespace }}:3200
      use_grpc: false
