---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: istio-addons-scc
  annotations:
    argocd.argoproj.io/sync-wave: "0"
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
seccompProfiles:
- '*'
priority: 9
users:
- system:serviceaccount:{{ .Values.istio.namespace }}:default
- system:serviceaccount:{{ .Values.istio.namespace }}:prometheus
- system:serviceaccount:{{ .Values.istio.namespace }}:grafana
