---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-kiali
  namespace: {{ .Values.operators.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  config:
    env:
    - name: ALLOW_ALL_ACCESSIBLE_NAMESPACES
      value: "true"
    - name: ACCESSIBLE_NAMESPACES_LABEL
      value: ""
