apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ocp5-first-look-lab
  title: ocp5-first-look-lab
  description: 'Red Hat OpenShift 5: First Look Lab'
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: gmidha1
    ph.rhdp.io/owner: gmidha@redhat.com
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/ocp5-first-look-lab
    ph.rhdp.io/created-at: 2026-09-21 11:03:47.517000+00:00
  tags:
  - publishing-house
  - lab
  - rhdp-published
  links:
  - url: https://github.com/rhpds/ocp5-first-look-lab
    title: Repository
    icon: github
  - url: https://devspaces.apps.ocpv-infra02.wdc07.infra.demo.redhat.com#https://github.com/rhpds/ocp5-first-look-lab
    title: Open in DevSpaces
    icon: catalog
  - url: https://central-api-publishing-house.apps.ocpv-infra02.wdc07.infra.demo.redhat.com
    title: Central
    icon: dashboard
  - url: https://redhat.atlassian.net/browse/RHDPCD-2035
    title: Jira Epic
    icon: dashboard
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
