---
site:
  title: Red Hat OpenShift 5 - First Look
  url: https://github.com/rhpds/ocp5-first-look-lab
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/v2.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www