---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: ">_ Terminals"
    path: /wetty
    port: 443
    secondary_name: OCP Terminal
    secondary_path: /codeserver
    secondary_port: 443
