{{- if .Values.gateway.clusterSubdomain }}
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: mcp-tool-auth-policy
  namespace: {{ .Values.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
    sectionName: mcps
  rules:
    authentication:
      keycloak-jwt:
        jwt:
          issuerUrl: https://sso.{{ .Values.gateway.clusterSubdomain }}/realms/{{ .Values.keycloak.realm }}
        credentials:
          authorizationHeader:
            prefix: Bearer
    authorization:
      tool-access-check:
        when:
          - predicate: "request.headers.exists(h, h == 'x-mcp-toolname')"
        patternMatching:
          patterns:
            - predicate: |
                ('tool:' + request.headers['x-mcp-toolname']) in (has(auth.identity.resource_access) && auth.identity.resource_access.exists(p, p == request.headers['x-mcp-servername']) ? auth.identity.resource_access[request.headers['x-mcp-servername']].roles : [])
    response:
      unauthenticated:
        headers:
          WWW-Authenticate:
            value: "Bearer resource_metadata=http://mcp.{{ .Values.gateway.clusterSubdomain }}/.well-known/oauth-protected-resource/mcp"
        body:
          value: |
            {
              "error": "Unauthorized",
              "message": "MCP Access denied: Authentication required."
            }
      unauthorized:
        body:
          value: |
            {
              "error": "Forbidden",
              "message": "MCP Access denied: Insufficient permissions for this tool."
            }
{{- end }}
