nameOverride: ""

clusterName: local-cluster

adminPassword: ""

clusterSubdomain: ""

clusterIssuer: acme-bifrost-production-ddns

vmScanning:
  enabled: true

argocd:
  enabled: true
  syncwave: "2"
