nameOverride: ""

clusterName: local-cluster

adminPassword: ""

clusterSubdomain: ""

clusterIssuer: acme-bifrost-production-ddns

centralDb:
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 8Gi

vmScanning:
  enabled: true

argocd:
  enabled: true
  syncwave: "2"
